image: alpine

workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

stages:
  - wasm
  - pages

build_wasm:
  image: rpigab/rust-wasm-pack:1.74
  stage: wasm
  script:
    - cd wasm
    - wasm-pack build --target web --out-dir ./web/pkg --no-typescript
  artifacts:
    paths:
      - wasm/web/
    expire_in: 1h

pages:
  stage: pages
  needs:
    - job: build_wasm
      artifacts: true
  script:
    - mv wasm/web public
  artifacts:
    paths:
      - public
